services:
  - type: web
    name: ayurveda-expert-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        value: "GROQ_API_KEY="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"
      - key: QDRANT_URL
        value: "https://5b0cccfe-e220-49b7-8f69-2bf1a5a7b7f6.europe-west3-0.gcp.cloud.qdrant.io"
      - key: QDRANT_API_KEY
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.G_vy07rJjatgXFY2pzi_73Czs4ciz0E_caYEnWTs1rU"
