name: Build and deploy Python app to Azure Web App - myayurbot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Optional: sanity check deps resolve
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/
            !.git/
            !**/__pycache__/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9257B96EB22F4F84B5A75E1C0A910BC4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_34C9FA5108974475B475012C7A656656 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4EEACED662134CB08029799526A5861D }}

      # One-time (idempotent) configuration of app settings & startup
      - name: Configure app settings and startup
        run: |
          az webapp config appsettings set -g "<YOUR_RESOURCE_GROUP>" -n "myayurbot" --settings \
            QDRANT_URL="${{ secrets.QDRANT_URL }}" \
            QDRANT_API_KEY="${{ secrets.QDRANT_API_KEY }}" \
            GROQ_API_KEY="${{ secrets.GROQ_API_KEY }}" \
            WEBSITES_PORT="8000"
          az webapp config set -g "<YOUR_RESOURCE_GROUP>" -n "myayurbot" \
            --startup-file 'gunicorn -k uvicorn.workers.UvicornWorker -w 2 -b 0.0.0.0:$PORT app:app'

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'myayurbot'
          slot-name: 'Production'
